/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in source so the
// scaffold can type-check once dependencies are installed.
